/**
 * Stock palette generator for dsh-web-visualuiconfig.
 *
 * Reads the DeepSeek Harness UI theme source (`design-platform.css`) and emits
 * `src/shared/stock.generated.ts` — the 73-step `--dsw-static-*` palette, its
 * raw hexes, and the `--dsw-alias-*` semantic layer, all pre-converted to
 * OKLCh. The browser cannot read a CSS file off disk, so it derives character
 * themes from the numbers this script extracted; the Host and the browser share
 * one stock, and a change to upstream's palette reaches both through one
 * regenerate.
 *
 * The parse and the OKLCh conversion are ported from deepseek-harness-skin's
 * `scripts/build-skins.mjs` (MIT, © 2026 HeiGeAi / Blake Xu —
 * https://github.com/HeiGeAi/deepseek-harness-skin); this script only emits the
 * stock module (no built-in skin CSS — this plugin derives themes at runtime).
 *
 * Usage:
 *   node --import tsx scripts/build-stock.mjs --harness <deepseek-harness-root>
 *   node --import tsx scripts/build-stock.mjs --css <path-to-design-platform.css>
 *   DSH_HARNESS=<root> node --import tsx scripts/build-stock.mjs
 *   ... --check   verify the generated module matches the source (exit 1 on
 *                 drift) instead of writing it.
 */
import { readFileSync, writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'
import { hexToOklch, parseColor } from '../src/shared/color.ts'
import { auditSkin, deriveSkin } from '../src/shared/derive.ts'

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..')
const OUT = join(ROOT, 'src', 'shared', 'stock.generated.ts')

const args = process.argv.slice(2)
const check = args.includes('--check')
const flag = (name) => {
  const at = args.indexOf(`--${name}`)
  return at === -1 ? undefined : args[at + 1]
}
const cssPath = flag('css')
const harness = flag('harness') ?? process.env.DSH_HARNESS
const PLATFORM = cssPath ?? (harness === undefined ? undefined : join(harness, 'packages', 'client', 'ui-theme', 'src', 'styles', 'design-platform.css'))
if (PLATFORM === undefined) {
  console.error('usage: node --import tsx scripts/build-stock.mjs --harness <deepseek-harness-root> | --css <design-platform.css> | DSH_HARNESS=<root>')
  process.exit(1)
}

// ── upstream palette ────────────────────────────────────────────────────────

/**
 * Read the stock palette out of design-platform.css. The palette is absolute —
 * both scheme blocks declare identical steps, and the schemes diverge only at
 * the semantic layer — so every static declaration in the file is read and the
 * families are keyed by name.
 * @returns `{ families, hex }` — steps grouped by family in OKLCh, plus the raw
 *          hex of every step.
 */
function readStockPalette() {
  const src = readFileSync(PLATFORM, 'utf8')
  const hex = {}
  const families = {}
  for (const m of src.matchAll(/(--dsw-static-[a-z0-9-]+)\s*:\s*([^;]+);/g)) {
    const name = m[1]
    if (hex[name] !== undefined) continue
    const value = m[2].trim()
    hex[name] = `#${parseColor(value).map(c => c.toString(16).padStart(2, '0')).join('')}`
    const family = name.replace(/-\d+(-delete)?$/, '')
    const [L, C, h] = hexToOklch(value)
    families[family] ??= []
    families[family].push({ name, L, C, h })
  }
  for (const steps of Object.values(families)) steps.sort((a, b) => b.L - a.L)
  return { families, hex }
}

/**
 * Read upstream's semantic layer for both schemes. These declarations are
 * mostly `var(--dsw-static-*)` references, so resolving them against a skin's
 * palette yields the colours that skin actually paints — which is what the
 * readability audit has to measure, rather than a proxy palette step.
 * @returns `{ light, dark }`, each token name → raw declaration.
 */
function readStockAliases() {
  const src = readFileSync(PLATFORM, 'utf8')
  const light = {}
  const dark = {}
  for (const m of src.matchAll(/(body(?:\[data-ds-dark-theme\])?)\s*\{(.*?)\n\}/gs)) {
    const target = m[1].includes('dark') ? dark : light
    for (const decl of m[2].matchAll(/(--[a-z0-9-]+)\s*:\s*([^;]+);/g)) {
      if (decl[1].startsWith('--dsw-static-')) continue
      target[decl[1]] = decl[2].trim()
    }
  }
  return { light, dark }
}

// ── emit ────────────────────────────────────────────────────────────────────

const BANNER = `/* GENERATED by scripts/build-stock.mjs — do not edit.
 * Source of truth: <deepseek-harness>/packages/client/ui-theme/src/styles/design-platform.css
 * Regenerate: pnpm build:stock -- --harness <deepseek-harness-root> */`

/** Emit upstream's parsed palette as data. */
function renderStock(families, hex, aliases) {
  const num = value => Number(value.toFixed(6))
  const str = value => `'${value.replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`
  const steps = family => families[family]
    .map(s => `      { name: '${s.name}', L: ${num(s.L)}, C: ${num(s.C)}, h: ${num(s.h)} },`)
    .join('\n')
  const familyRows = Object.keys(families).sort()
    .map(family => `    '${family}': [\n${steps(family)}\n    ],`).join('\n')
  const hexRows = Object.keys(hex).sort().map(name => `    '${name}': '${hex[name]}',`).join('\n')
  const aliasRows = scheme => Object.keys(aliases[scheme]).sort()
    .map(name => `      '${name}': ${str(aliases[scheme][name])},`).join('\n')
  return `${BANNER}

import type { StockData } from './stock.ts'

/**
 * Upstream's palette and semantic layer, extracted from design-platform.css.
 * Regenerating after an upstream palette change is what keeps built-in themes
 * and browser-derived character themes on the same ramp.
 */
export const STOCK: StockData = {
  families: {
${familyRows}
  },
  hex: {
${hexRows}
  },
  aliases: {
    light: {
${aliasRows('light')}
    },
    dark: {
${aliasRows('dark')}
    },
  },
}
`
}

// ── run ─────────────────────────────────────────────────────────────────────

const { families, hex } = readStockPalette()
const aliases = readStockAliases()
const stock = { families, hex, aliases }
const want = renderStock(families, hex, aliases)

// Smoke gate: a plausible light character-theme palette must derive and clear
// the readability contract. A broken stock (missing family/step/alias) fails
// loudly here rather than surfacing later as a broken-looking theme.
const smoke = {
  id: 'smoke',
  appearance: 'light',
  chrome: 'glass',
  seeds: { accent: '#1a7f8c', secondary: '#8c5a1a', surface: '#f4f1ea', text: '#241f1a' },
}
const derived = deriveSkin(smoke, stock)
const failed = auditSkin(smoke, derived, stock).filter(entry => !entry.pass)
if (failed.length > 0) {
  console.error(`❌ stock smoke audit failed: ${failed.map(f => `${f.label} ${f.ratio?.toFixed(2) ?? '—'} < ${f.min}`).join(', ')}`)
  process.exit(1)
}

if (check) {
  let got = null
  try { got = readFileSync(OUT, 'utf8') } catch { /* missing counts as drift */ }
  if (got !== want) {
    console.error(`drift: ${OUT} does not match ${PLATFORM}; run pnpm build:stock`)
    process.exit(1)
  }
  console.log(`✅ ${OUT} matches ${PLATFORM} (${Object.keys(families).length} families, ${Object.keys(hex).length} steps, ${Object.keys(aliases.light).length}+${Object.keys(aliases.dark).length} aliases)`)
} else {
  writeFileSync(OUT, want)
  console.log(`✅ wrote ${OUT} from ${PLATFORM} (${Object.keys(families).length} families, ${Object.keys(hex).length} steps, ${Object.keys(aliases.light).length}+${Object.keys(aliases.dark).length} aliases)`)
}
